apiVersion: v1
kind: Template
labels:
  template: f8a-github-events-monitor
metadata:
  name: f8a-github-events-monitor
  annotations:
    description: f8a-github-events-monitor
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: f8a-github-events-monitor
    name: f8a-github-events-monitor
  spec:
    replicas: ${{REPLICAS}}
    selector:
      service: f8a-github-events-monitor
    template:
      metadata:
        labels:
          service: f8a-github-events-monitor
      spec:
        containers:
        - env:
          - name: DEPLOYMENT_PREFIX
            valueFrom:
              configMapKeyRef:
                name: bayesian-config
                key: deployment-prefix
          - name: WORKER_ADMINISTRATION_REGION
            value: "api"
          - name: AWS_SQS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws
                key: sqs-access-key-id
          - name: AWS_SQS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws
                key: sqs-secret-access-key
          - name: AWS_S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
               name: aws
               key: s3-access-key-id
          - name: AWS_S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws
                key: s3-secret-access-key
          # this won't get used if running with SQS
          - name: RABBITMQ_SERVICE_SERVICE_HOST
            value: bayesian-broker
          - name: PGBOUNCER_SERVICE_HOST
            value: bayesian-pgbouncer
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: database
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: username
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: password
          - name: GITHUB_TOKEN
            value: ${GITHUB_TOKEN}
          - name: SLEEP_PERIOD
            value: ${SLEEP_PERIOD}
          - name: WATCH_PACKAGES
            value: ${WATCH_PACKAGES}
          - name: LOGLEVEL
            value: ${LOGLEVEL}
          image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
          name: f8a-github-events-monitor
          # TODO: if we want this, we need to implement in the app
          # livenessProbe:
          #   exec:
          #     command:
          #     - cat
          #     - /tmp/release_monitoring/liveness.txt
          #   initialDelaySeconds: 30
          #   periodSeconds: 60
          #   timeoutSeconds: 30
          # readinessProbe:
          #   exec:
          #     command:
          #     - cat
          #     - /tmp/release_monitoring/liveness.txt
          #   initialDelaySeconds: 30
          #   periodSeconds: 60
          #   timeoutSeconds: 30
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: f8a-github-events-monitor
    name: f8a-github-events-monitor
  spec:
    ports:
    - name: "35000"
      port: 35000
      protocol: TCP
      targetPort: 35000
    selector:
      service: f8a-github-events-monitor

parameters:
- description: Docker registry where the image is
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "quay.io"

          - name: GITHUB_TOKEN
          - name: SLEEP_PERIOD
          - name: WATCH_PACKAGES
          - name: LOGLEVEL

- description: Define Github token for increased API Rate Limit
  displayName: Github API token
  required: true
  name: GITHUB_TOKEN
  value: ""

- description: Variable which defines the time between updates (in seconds)
  displayName: Sleep period
  name: SLEEP_PERIOD
  value: "600"

- description: Golang packages which we want to monitor
  displayName: Go packages to watch
  name: WATCH_PACKAGES
  value: "k8s.io/metrics"

- description: Define level of verbosity
  displayName: Logging verbosity
  name: LOGLEVEL
  value: "INFO"


- description: Docker image to use
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "openshiftio/fabric8-analytics-f8a-github-events-monitor"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"  # image-tag

- description: Number of deployment replicas
  displayName: Number of deployment replicas
  required: true
  name: REPLICAS
  value: "1"

# - description: Liveness probe file location
#   displayName: Liveness probe file location
#   required: true
#   name: PROBE_FILE_LOCATION
#   value: "/tmp/release_monitoring/liveness.txt"
